
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package SyntacticalAnalizer;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int NUMERO = 49;
  public static final int DOSPUNTOS = 46;
  public static final int DISTINTO = 32;
  public static final int AVANCE = 7;
  public static final int CASO = 26;
  public static final int PUBLICO = 17;
  public static final int Y = 2;
  public static final int DEVOLVER = 12;
  public static final int LLAVECERRADO = 43;
  public static final int IMPRIMIR = 19;
  public static final int SI = 10;
  public static final int O = 3;
  public static final int RESTA = 36;
  public static final int DESDE = 5;
  public static final int NEGATIVO = 39;
  public static final int HASTA = 6;
  public static final int PRIVADO = 18;
  public static final int CAD = 15;
  public static final int MAYORQUE = 29;
  public static final int IGUAL = 33;
  public static final int PARENTESISCERRADO = 45;
  public static final int SINO = 11;
  public static final int MIENTRAS = 8;
  public static final int BOOL = 16;
  public static final int SUMA = 35;
  public static final int NUM = 23;
  public static final int SALIR = 48;
  public static final int EOF = 0;
  public static final int LLAVEABIERTO = 42;
  public static final int MAYOROIGUAL = 31;
  public static final int CLASE = 14;
  public static final int error = 1;
  public static final int COMA = 47;
  public static final int REVISAR = 25;
  public static final int CADENA = 51;
  public static final int NEGACION = 24;
  public static final int CORCHETECERRADO = 41;
  public static final int ASIGNACION = 34;
  public static final int MENOROIGUAL = 30;
  public static final int MENORQUE = 28;
  public static final int PARENTESISABIERTO = 44;
  public static final int FALSO = 22;
  public static final int LEER = 20;
  public static final int HACER = 9;
  public static final int PROC = 13;
  public static final int PARA = 4;
  public static final int VERDADERO = 21;
  public static final int DIVISION = 38;
  public static final int CORCHETEABIERTO = 40;
  public static final int DEFECTO = 27;
  public static final int VAR = 50;
  public static final int MULTIPLICACION = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Y",
  "O",
  "PARA",
  "DESDE",
  "HASTA",
  "AVANCE",
  "MIENTRAS",
  "HACER",
  "SI",
  "SINO",
  "DEVOLVER",
  "PROC",
  "CLASE",
  "CAD",
  "BOOL",
  "PUBLICO",
  "PRIVADO",
  "IMPRIMIR",
  "LEER",
  "VERDADERO",
  "FALSO",
  "NUM",
  "NEGACION",
  "REVISAR",
  "CASO",
  "DEFECTO",
  "MENORQUE",
  "MAYORQUE",
  "MENOROIGUAL",
  "MAYOROIGUAL",
  "DISTINTO",
  "IGUAL",
  "ASIGNACION",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "NEGATIVO",
  "CORCHETEABIERTO",
  "CORCHETECERRADO",
  "LLAVEABIERTO",
  "LLAVECERRADO",
  "PARENTESISABIERTO",
  "PARENTESISCERRADO",
  "DOSPUNTOS",
  "COMA",
  "SALIR",
  "NUMERO",
  "VAR",
  "CADENA"
  };
}

