package LexicalAnalizer;/* The following code was generated by JFlex 1.6.1 */

import java_cup.runtime.*;
import java.io.Reader;
/*
Mathison

Instrucciones para correr el analizador léxico:
1. Compilar el archivo lexer1.jflex con Jflex
2. Se generará el archivo Lexer.java y se corre con algún IDE con soporte para Java
3. Se ingresan las palabras, cadenas, numeros o símbolos por medio de línea de
comando o en un archivo de texto
4. Las reglas son las siguientes:
	- Las variables deben empezar con una letra y pueden tener solamente letras,
	números y guiones bajos
	- Los números pueden ser negativos o positivos y pueden tener o no decimales
	separados por un punto
	- Las palabras reservadas se pueden escribir en mayúsculas, minúsculas o
	con un combinación de ambas, estas se listan más abajo
	- Los comentarios se escriben con dos slash, para comentarios de una
	línea o con slash-asterisco asterisco-slash, para comentarios multilínea
	y ambos aceptan cualquier caracter
	- Los literales de cadena se escriben entre comillas y aceptan cualquier
	carecter que no sean comillas a menos que esten precedidas por un backslash
	- Se pueden escribir expresiones separadas o no por espacios que serán
	identificadas por el analizador, esto no aplica para comentarios o literales
	de cadena donde identifica toda la expresión como una sola
*/
import SintacticalAnalizer.sym;
/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/Oscar Azofeifa/IdeaProjects/MathisonCompiler/src/main/resources/LexerSources/lexer1.jflex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\42\1\37\1\0\1\42\1\37\22\0\1\42\1\47\1\43"+
    "\5\0\1\54\1\55\1\41\1\46\1\0\1\32\1\34\1\40\12\33"+
    "\1\56\1\0\1\27\1\30\1\31\2\0\1\4\1\22\1\15\1\6"+
    "\1\7\1\23\1\35\1\11\1\17\1\26\1\35\1\20\1\16\1\14"+
    "\1\2\1\3\1\35\1\5\1\10\1\12\1\21\1\13\1\35\1\25"+
    "\1\1\1\24\1\50\1\44\1\51\1\45\1\36\1\0\1\4\1\22"+
    "\1\15\1\6\1\7\1\23\1\35\1\11\1\17\1\26\1\35\1\20"+
    "\1\16\1\14\1\2\1\3\1\35\1\5\1\10\1\12\1\21\1\13"+
    "\1\35\1\25\1\1\1\24\1\52\1\0\1\53\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff92\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\20\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\1\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\7\4\1\27\2\4\1\30\16\4\1\31\1\32\1\33"+
    "\1\0\1\34\2\0\1\35\1\0\7\4\1\36\11\4"+
    "\1\37\1\40\1\4\1\41\2\4\1\42\7\4\1\43"+
    "\1\11\1\34\4\0\1\44\1\45\12\4\1\46\5\4"+
    "\1\47\1\50\7\4\1\51\1\52\1\4\1\0\5\4"+
    "\1\53\4\4\1\54\1\55\3\4\1\56\12\4\1\57"+
    "\15\4\1\60\1\4\1\61\1\62\1\63\1\64\1\4"+
    "\1\65\1\66\4\4\1\67\5\4\1\70\1\71\1\72"+
    "\2\4\1\73\1\74\1\75\1\76\1\4\1\77\1\100"+
    "\1\4\1\101";

  private static int [] zzUnpackAction() {
    int [] result = new int[215];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\136\0\215\0\274\0\353\0\u011a"+
    "\0\u0149\0\u0178\0\u01a7\0\u01d6\0\136\0\u0205\0\u0234\0\u0263"+
    "\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db"+
    "\0\u040a\0\57\0\u0439\0\57\0\u0468\0\57\0\57\0\57"+
    "\0\57\0\57\0\57\0\57\0\57\0\57\0\57\0\u0497"+
    "\0\u04c6\0\u04f5\0\u0524\0\u0553\0\u0582\0\u05b1\0\136\0\u05e0"+
    "\0\u060f\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa\0\u0729\0\u0758"+
    "\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872\0\u08a1\0\u08d0"+
    "\0\57\0\57\0\57\0\u08ff\0\u092e\0\u095d\0\u098c\0\57"+
    "\0\u09bb\0\u09ea\0\u0a19\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04"+
    "\0\136\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d"+
    "\0\u0c7c\0\u0cab\0\136\0\u0cda\0\u0d09\0\136\0\u0d38\0\u0d67"+
    "\0\136\0\u0d96\0\u0dc5\0\u0df4\0\u0e23\0\u0e52\0\u0e81\0\u0eb0"+
    "\0\u0edf\0\u08ff\0\57\0\u0f0e\0\u0f3d\0\u0468\0\u0f6c\0\136"+
    "\0\136\0\u0f9b\0\u0fca\0\u0ff9\0\u1028\0\u1057\0\u1086\0\u10b5"+
    "\0\u10e4\0\u1113\0\u1142\0\136\0\u1171\0\u11a0\0\u11cf\0\u11fe"+
    "\0\u122d\0\136\0\136\0\u125c\0\u128b\0\u12ba\0\u12e9\0\u1318"+
    "\0\u1347\0\u1376\0\136\0\136\0\u13a5\0\u13d4\0\u1403\0\u1432"+
    "\0\u1461\0\u1490\0\u14bf\0\136\0\u14ee\0\u151d\0\u154c\0\u157b"+
    "\0\136\0\136\0\u15aa\0\u15d9\0\u1608\0\136\0\u1637\0\u1666"+
    "\0\u1695\0\u16c4\0\u16f3\0\u1722\0\u1751\0\u1780\0\u17af\0\u17de"+
    "\0\136\0\u180d\0\u183c\0\u186b\0\u189a\0\u18c9\0\u18f8\0\u1927"+
    "\0\u1956\0\u1985\0\u19b4\0\u19e3\0\u1a12\0\u1a41\0\136\0\u1a70"+
    "\0\136\0\136\0\136\0\136\0\u1a9f\0\136\0\136\0\u1ace"+
    "\0\u1afd\0\u1b2c\0\u1b5b\0\136\0\u1b8a\0\u1bb9\0\u1be8\0\u1c17"+
    "\0\u1c46\0\136\0\136\0\136\0\u1c75\0\u1ca4\0\136\0\136"+
    "\0\136\0\136\0\u1cd3\0\136\0\136\0\u1d02\0\136";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[215];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\15\1\23\1\24\3\15\1\25\1\26\1\27"+
    "\1\30\1\31\1\2\1\15\1\2\1\32\1\33\1\34"+
    "\1\32\1\35\1\2\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\60\0\26\15\4\0"+
    "\1\15\1\0\2\15\21\0\3\15\1\50\1\51\13\15"+
    "\1\52\5\15\4\0\1\15\1\0\2\15\21\0\11\15"+
    "\1\53\1\54\13\15\4\0\1\15\1\0\2\15\21\0"+
    "\6\15\1\55\17\15\4\0\1\15\1\0\2\15\21\0"+
    "\6\15\1\56\17\15\4\0\1\15\1\0\2\15\21\0"+
    "\13\15\1\57\10\15\1\60\1\61\4\0\1\15\1\0"+
    "\2\15\21\0\16\15\1\62\7\15\4\0\1\15\1\0"+
    "\2\15\21\0\3\15\1\63\22\15\4\0\1\15\1\0"+
    "\2\15\21\0\6\15\1\64\17\15\4\0\1\15\1\0"+
    "\2\15\21\0\20\15\1\65\5\15\4\0\1\15\1\0"+
    "\2\15\21\0\1\15\1\66\1\15\1\67\13\15\1\70"+
    "\6\15\4\0\1\15\1\0\2\15\21\0\1\15\1\71"+
    "\14\15\1\72\7\15\4\0\1\15\1\0\2\15\21\0"+
    "\13\15\1\73\1\15\1\74\10\15\4\0\1\15\1\0"+
    "\2\15\21\0\3\15\1\75\2\15\1\76\17\15\4\0"+
    "\1\15\1\0\2\15\21\0\1\15\1\77\24\15\4\0"+
    "\1\15\1\0\2\15\21\0\16\15\1\100\7\15\4\0"+
    "\1\15\1\0\2\15\50\0\1\101\56\0\1\102\56\0"+
    "\1\103\61\0\1\31\56\0\1\31\1\104\62\0\1\105"+
    "\1\106\15\0\43\107\1\110\1\111\12\107\1\0\4\15"+
    "\1\112\21\15\4\0\1\15\1\0\2\15\21\0\1\15"+
    "\1\113\14\15\1\114\7\15\4\0\1\15\1\0\2\15"+
    "\21\0\21\15\1\115\4\15\4\0\1\15\1\0\2\15"+
    "\21\0\4\15\1\116\21\15\4\0\1\15\1\0\2\15"+
    "\21\0\3\15\1\117\22\15\4\0\1\15\1\0\2\15"+
    "\21\0\12\15\1\120\1\15\1\121\11\15\4\0\1\15"+
    "\1\0\2\15\21\0\7\15\1\122\2\15\1\123\7\15"+
    "\1\124\3\15\4\0\1\15\1\0\2\15\21\0\14\15"+
    "\1\125\11\15\4\0\1\15\1\0\2\15\21\0\6\15"+
    "\1\126\17\15\4\0\1\15\1\0\2\15\21\0\13\15"+
    "\1\127\12\15\4\0\1\15\1\0\2\15\21\0\7\15"+
    "\1\130\4\15\1\131\11\15\4\0\1\15\1\0\2\15"+
    "\21\0\4\15\1\132\21\15\4\0\1\15\1\0\2\15"+
    "\21\0\15\15\1\133\10\15\4\0\1\15\1\0\2\15"+
    "\21\0\13\15\1\134\1\15\1\135\10\15\4\0\1\15"+
    "\1\0\2\15\21\0\5\15\1\136\1\15\1\137\16\15"+
    "\4\0\1\15\1\0\2\15\21\0\3\15\1\140\22\15"+
    "\4\0\1\15\1\0\2\15\21\0\5\15\1\141\1\15"+
    "\1\142\16\15\4\0\1\15\1\0\2\15\21\0\6\15"+
    "\1\143\17\15\4\0\1\15\1\0\2\15\21\0\11\15"+
    "\1\144\14\15\4\0\1\15\1\0\2\15\21\0\2\15"+
    "\1\145\23\15\4\0\1\15\1\0\2\15\21\0\13\15"+
    "\1\146\12\15\4\0\1\15\1\0\2\15\21\0\6\15"+
    "\1\147\17\15\4\0\1\15\1\0\2\15\21\0\1\15"+
    "\1\150\24\15\4\0\1\15\1\0\2\15\21\0\13\15"+
    "\1\151\12\15\4\0\1\15\1\0\2\15\53\0\1\152"+
    "\23\0\37\105\1\153\17\105\41\154\1\155\15\154\43\156"+
    "\1\110\1\157\56\156\1\157\12\156\1\0\3\15\1\160"+
    "\22\15\4\0\1\15\1\0\2\15\21\0\14\15\1\161"+
    "\11\15\4\0\1\15\1\0\2\15\21\0\12\15\1\162"+
    "\13\15\4\0\1\15\1\0\2\15\21\0\17\15\1\163"+
    "\6\15\4\0\1\15\1\0\2\15\21\0\3\15\1\164"+
    "\22\15\4\0\1\15\1\0\2\15\21\0\13\15\1\165"+
    "\12\15\4\0\1\15\1\0\2\15\21\0\16\15\1\166"+
    "\7\15\4\0\1\15\1\0\2\15\21\0\5\15\1\167"+
    "\20\15\4\0\1\15\1\0\2\15\21\0\1\15\1\170"+
    "\24\15\4\0\1\15\1\0\2\15\21\0\6\15\1\171"+
    "\17\15\4\0\1\15\1\0\2\15\21\0\6\15\1\172"+
    "\17\15\4\0\1\15\1\0\2\15\21\0\14\15\1\173"+
    "\11\15\4\0\1\15\1\0\2\15\21\0\1\15\1\174"+
    "\24\15\4\0\1\15\1\0\2\15\21\0\11\15\1\175"+
    "\14\15\4\0\1\15\1\0\2\15\21\0\6\15\1\176"+
    "\17\15\4\0\1\15\1\0\2\15\21\0\15\15\1\177"+
    "\10\15\4\0\1\15\1\0\2\15\21\0\7\15\1\200"+
    "\1\15\1\201\14\15\4\0\1\15\1\0\2\15\21\0"+
    "\1\15\1\202\24\15\4\0\1\15\1\0\2\15\21\0"+
    "\1\15\1\203\24\15\4\0\1\15\1\0\2\15\21\0"+
    "\7\15\1\204\16\15\4\0\1\15\1\0\2\15\21\0"+
    "\11\15\1\205\14\15\4\0\1\15\1\0\2\15\21\0"+
    "\13\15\1\206\12\15\4\0\1\15\1\0\2\15\21\0"+
    "\6\15\1\207\17\15\4\0\1\15\1\0\2\15\21\0"+
    "\1\15\1\210\2\15\1\211\21\15\4\0\1\15\1\0"+
    "\2\15\21\0\23\15\1\212\2\15\4\0\1\15\1\0"+
    "\2\15\21\0\4\15\1\213\21\15\4\0\1\15\1\0"+
    "\2\15\21\0\17\15\1\214\6\15\4\0\1\15\1\0"+
    "\2\15\21\0\3\15\1\215\22\15\4\0\1\15\1\0"+
    "\2\15\20\0\41\154\1\216\15\154\40\0\1\153\1\155"+
    "\15\0\43\107\1\0\1\111\12\107\1\0\3\15\1\217"+
    "\22\15\4\0\1\15\1\0\2\15\21\0\16\15\1\220"+
    "\7\15\4\0\1\15\1\0\2\15\21\0\2\15\1\221"+
    "\23\15\4\0\1\15\1\0\2\15\21\0\14\15\1\222"+
    "\11\15\4\0\1\15\1\0\2\15\21\0\7\15\1\223"+
    "\16\15\4\0\1\15\1\0\2\15\21\0\6\15\1\224"+
    "\17\15\4\0\1\15\1\0\2\15\21\0\17\15\1\225"+
    "\6\15\4\0\1\15\1\0\2\15\21\0\14\15\1\226"+
    "\11\15\4\0\1\15\1\0\2\15\21\0\2\15\1\227"+
    "\23\15\4\0\1\15\1\0\2\15\21\0\20\15\1\230"+
    "\5\15\4\0\1\15\1\0\2\15\21\0\3\15\1\231"+
    "\22\15\4\0\1\15\1\0\2\15\21\0\4\15\1\232"+
    "\21\15\4\0\1\15\1\0\2\15\21\0\16\15\1\233"+
    "\7\15\4\0\1\15\1\0\2\15\21\0\11\15\1\234"+
    "\14\15\4\0\1\15\1\0\2\15\21\0\16\15\1\235"+
    "\7\15\4\0\1\15\1\0\2\15\21\0\6\15\1\236"+
    "\17\15\4\0\1\15\1\0\2\15\21\0\4\15\1\237"+
    "\21\15\4\0\1\15\1\0\2\15\21\0\11\15\1\240"+
    "\14\15\4\0\1\15\1\0\2\15\21\0\13\15\1\241"+
    "\12\15\4\0\1\15\1\0\2\15\21\0\4\15\1\242"+
    "\21\15\4\0\1\15\1\0\2\15\21\0\16\15\1\243"+
    "\7\15\4\0\1\15\1\0\2\15\21\0\3\15\1\244"+
    "\22\15\4\0\1\15\1\0\2\15\21\0\17\15\1\245"+
    "\6\15\4\0\1\15\1\0\2\15\20\0\40\154\1\153"+
    "\1\216\15\154\1\0\5\15\1\246\20\15\4\0\1\15"+
    "\1\0\2\15\21\0\14\15\1\247\11\15\4\0\1\15"+
    "\1\0\2\15\21\0\3\15\1\250\22\15\4\0\1\15"+
    "\1\0\2\15\21\0\6\15\1\251\17\15\4\0\1\15"+
    "\1\0\2\15\21\0\3\15\1\252\22\15\4\0\1\15"+
    "\1\0\2\15\21\0\12\15\1\253\13\15\4\0\1\15"+
    "\1\0\2\15\21\0\11\15\1\254\14\15\4\0\1\15"+
    "\1\0\2\15\21\0\11\15\1\255\14\15\4\0\1\15"+
    "\1\0\2\15\21\0\11\15\1\256\14\15\4\0\1\15"+
    "\1\0\2\15\21\0\13\15\1\257\12\15\4\0\1\15"+
    "\1\0\2\15\21\0\3\15\1\260\22\15\4\0\1\15"+
    "\1\0\2\15\21\0\13\15\1\261\12\15\4\0\1\15"+
    "\1\0\2\15\21\0\3\15\1\262\22\15\4\0\1\15"+
    "\1\0\2\15\21\0\4\15\1\263\21\15\4\0\1\15"+
    "\1\0\2\15\21\0\11\15\1\264\14\15\4\0\1\15"+
    "\1\0\2\15\21\0\11\15\1\265\14\15\4\0\1\15"+
    "\1\0\2\15\21\0\15\15\1\266\10\15\4\0\1\15"+
    "\1\0\2\15\21\0\4\15\1\267\21\15\4\0\1\15"+
    "\1\0\2\15\21\0\15\15\1\270\10\15\4\0\1\15"+
    "\1\0\2\15\21\0\1\15\1\271\24\15\4\0\1\15"+
    "\1\0\2\15\21\0\1\15\1\272\24\15\4\0\1\15"+
    "\1\0\2\15\21\0\4\15\1\273\21\15\4\0\1\15"+
    "\1\0\2\15\21\0\4\15\1\274\21\15\4\0\1\15"+
    "\1\0\2\15\21\0\6\15\1\275\17\15\4\0\1\15"+
    "\1\0\2\15\21\0\1\15\1\276\24\15\4\0\1\15"+
    "\1\0\2\15\21\0\1\15\1\277\24\15\4\0\1\15"+
    "\1\0\2\15\21\0\3\15\1\300\22\15\4\0\1\15"+
    "\1\0\2\15\21\0\3\15\1\301\22\15\4\0\1\15"+
    "\1\0\2\15\21\0\13\15\1\302\12\15\4\0\1\15"+
    "\1\0\2\15\21\0\20\15\1\303\5\15\4\0\1\15"+
    "\1\0\2\15\21\0\4\15\1\304\21\15\4\0\1\15"+
    "\1\0\2\15\21\0\3\15\1\305\22\15\4\0\1\15"+
    "\1\0\2\15\21\0\3\15\1\306\22\15\4\0\1\15"+
    "\1\0\2\15\21\0\3\15\1\307\22\15\4\0\1\15"+
    "\1\0\2\15\21\0\16\15\1\310\7\15\4\0\1\15"+
    "\1\0\2\15\21\0\6\15\1\311\17\15\4\0\1\15"+
    "\1\0\2\15\21\0\4\15\1\312\21\15\4\0\1\15"+
    "\1\0\2\15\21\0\4\15\1\313\21\15\4\0\1\15"+
    "\1\0\2\15\21\0\4\15\1\314\21\15\4\0\1\15"+
    "\1\0\2\15\21\0\11\15\1\315\14\15\4\0\1\15"+
    "\1\0\2\15\21\0\3\15\1\316\22\15\4\0\1\15"+
    "\1\0\2\15\21\0\7\15\1\317\16\15\4\0\1\15"+
    "\1\0\2\15\21\0\4\15\1\320\21\15\4\0\1\15"+
    "\1\0\2\15\21\0\4\15\1\321\21\15\4\0\1\15"+
    "\1\0\2\15\21\0\4\15\1\322\21\15\4\0\1\15"+
    "\1\0\2\15\21\0\13\15\1\323\12\15\4\0\1\15"+
    "\1\0\2\15\21\0\6\15\1\324\17\15\4\0\1\15"+
    "\1\0\2\15\21\0\4\15\1\325\21\15\4\0\1\15"+
    "\1\0\2\15\21\0\11\15\1\326\14\15\4\0\1\15"+
    "\1\0\2\15\21\0\6\15\1\327\17\15\4\0\1\15"+
    "\1\0\2\15\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7473];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\27\1\1\11\1\1\1\11\1\1\12\11"+
    "\31\1\3\11\1\0\1\1\2\0\1\11\1\0\41\1"+
    "\1\11\4\0\36\1\1\0\111\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[215];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    /*  Generamos un java_cup.Symbol para guardar el tipo de token
        encontrado */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }

    /* Generamos un Symbol para el tipo de token encontrado
       junto con su valor */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
  yybegin(YYINITIAL);
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 208) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Illegal character <" + yytext()+">");
            }
          case 66: break;
          case 2: 
            { return symbol(sym.Y);
            }
          case 67: break;
          case 3: 
            { return symbol(sym.O);
            }
          case 68: break;
          case 4: 
            { return symbol(sym.VAR, new String(yytext()));
            }
          case 69: break;
          case 5: 
            { return symbol(sym.MENORQUE);
            }
          case 70: break;
          case 6: 
            { return symbol(sym.ASIGNACION);
            }
          case 71: break;
          case 7: 
            { return symbol(sym.MAYORQUE);
            }
          case 72: break;
          case 8: 
            { return symbol(sym.RESTA);
            }
          case 73: break;
          case 9: 
            { return symbol(sym.NUMERO, new Double(yytext()));
            }
          case 74: break;
          case 10: 
            { /* no hacer nada */
            }
          case 75: break;
          case 11: 
            { return symbol(sym.DIVISION);
            }
          case 76: break;
          case 12: 
            { return symbol(sym.MULTIPLICACION);
            }
          case 77: break;
          case 13: 
            { return symbol(sym.POTENCIA);
            }
          case 78: break;
          case 14: 
            { return symbol(sym.SUMA);
            }
          case 79: break;
          case 15: 
            { return symbol(sym.DISTINTO);
            }
          case 80: break;
          case 16: 
            { return symbol(sym.CORCHETEABIERTO);
            }
          case 81: break;
          case 17: 
            { return symbol(sym.CORCHETECERRADO);
            }
          case 82: break;
          case 18: 
            { return symbol(sym.LLAVEABIERTO);
            }
          case 83: break;
          case 19: 
            { return symbol(sym.LLAVECERRADO);
            }
          case 84: break;
          case 20: 
            { return symbol(sym.PARENTESISABIERTO);
            }
          case 85: break;
          case 21: 
            { return symbol(sym.PARENTESISCERRADO);
            }
          case 86: break;
          case 22: 
            { return symbol(sym.DOSPUNTOS);
            }
          case 87: break;
          case 23: 
            { return symbol(sym.EN);
            }
          case 88: break;
          case 24: 
            { return symbol(sym.SI);
            }
          case 89: break;
          case 25: 
            { return symbol(sym.MENOROIGUAL);
            }
          case 90: break;
          case 26: 
            { return symbol(sym.IGUAL);
            }
          case 91: break;
          case 27: 
            { return symbol(sym.MAYOROIGUAL);
            }
          case 92: break;
          case 28: 
            { /* no haceer nada*/
            }
          case 93: break;
          case 29: 
            { return symbol(sym.CADENA,new String(yytext()));
            }
          case 94: break;
          case 30: 
            { return symbol(sym.REC);
            }
          case 95: break;
          case 31: 
            { return symbol(sym.NUM);
            }
          case 96: break;
          case 32: 
            { return symbol(sym.CON);
            }
          case 97: break;
          case 33: 
            { return symbol(sym.CAD);
            }
          case 98: break;
          case 34: 
            { return symbol(sym.MOD);
            }
          case 99: break;
          case 35: 
            { return symbol(sym.FIN);
            }
          case 100: break;
          case 36: 
            { return symbol(sym.PARA);
            }
          case 101: break;
          case 37: 
            { return symbol(sym.PROC);
            }
          case 102: break;
          case 38: 
            { return symbol(sym.SINO);
            }
          case 103: break;
          case 39: 
            { return symbol(sym.COMO);
            }
          case 104: break;
          case 40: 
            { return symbol(sym.CASO);
            }
          case 105: break;
          case 41: 
            { return symbol(sym.LEER);
            }
          case 106: break;
          case 42: 
            { return symbol(sym.BOOL);
            }
          case 107: break;
          case 43: 
            { return symbol(sym.DESDE);
            }
          case 108: break;
          case 44: 
            { return symbol(sym.HASTA);
            }
          case 109: break;
          case 45: 
            { return symbol(sym.HACER);
            }
          case 110: break;
          case 46: 
            { return symbol(sym.CLASE);
            }
          case 111: break;
          case 47: 
            { return symbol(sym.AVANCE);
            }
          case 112: break;
          case 48: 
            { return symbol(sym.LANZAR);
            }
          case 113: break;
          case 49: 
            { return symbol(sym.PRIVADO);
            }
          case 114: break;
          case 50: 
            { return symbol(sym.PUBLICO);
            }
          case 115: break;
          case 51: 
            { return symbol(sym.ATRAPAR);
            }
          case 116: break;
          case 52: 
            { return symbol(sym.REVISAR);
            }
          case 117: break;
          case 53: 
            { return symbol(sym.DEFECTO);
            }
          case 118: break;
          case 54: 
            { return symbol(sym.EXCEPTO);
            }
          case 119: break;
          case 55: 
            { return symbol(sym.MOSTRAR);
            }
          case 120: break;
          case 56: 
            { return symbol(sym.DEVOLVER);
            }
          case 121: break;
          case 57: 
            { return symbol(sym.EJECUTAR);
            }
          case 122: break;
          case 58: 
            { return symbol(sym.TERMINAR);
            }
          case 123: break;
          case 59: 
            { return symbol(sym.MIENTRAS);
            }
          case 124: break;
          case 60: 
            { return symbol(sym.INTENTAR);
            }
          case 125: break;
          case 61: 
            { return symbol(sym.IMPORTAR);
            }
          case 126: break;
          case 62: 
            { return symbol(sym.IMPRIMIR);
            }
          case 127: break;
          case 63: 
            { return symbol(sym.CONSTANTE);
            }
          case 128: break;
          case 64: 
            { return symbol(sym.CONTINUAR);
            }
          case 129: break;
          case 65: 
            { return symbol(sym.FINALMENTE);
            }
          case 130: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexer(reader);
          while ( !scanner.zzAtEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
